name: Container Image Publish
on: [push]
jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile_Server"
          push: true
          tags: user/app:latest
